# Generated by Django 3.0.7 on 2020-11-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='birthday',
            new_name='Birthday',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='gender',
            new_name='Gender',
        ),
    ]
