# Generated by Django 3.0.7 on 2021-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201123_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='scanned_pic',
        ),
    ]
