# Generated by Django 3.0.7 on 2021-03-23 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
