# Generated by Django 3.0.7 on 2021-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210323_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
