# Generated by Django 3.0.7 on 2021-03-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210323_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
