# Generated by Django 3.0.7 on 2020-06-18 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthday', models.DateField(default=django.utils.timezone.now)),
                ('Gender', models.CharField(default='Male', max_length=10)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('cover_pic', models.ImageField(upload_to='cover_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
